export const state = {
  rollMods: {
    stunt: 3,
    explode: [],
    double: [10],
    autosuccesses: 2,
  },

  artifactRating: 5,

  resources: {
    willpower: {
      max: 1,
      current: 1,
    },

    successes: {
      current: 57,
      available: 34,
    },

    motes: {
      personal: 1,
      peripheral: 1,
    },
  },
}

export const character = {
  id: 90,
  created_at: "2018-03-29T04:39:50.077Z",
  updated_at: "2018-11-03T03:56:46.525Z",
  player_id: 66,
  type: "SolarCharacter",
  sort_order: 1522298400,
  hidden: false,
  pinned: true,
  public: true,
  chronicle_id: null,
  chronicle_sort_order: 1522298399,
  initiative: 0,
  onslaught: 0,
  in_combat: false,
  has_acted: false,
  name: "Lauded Iron",
  essence: 2,
  description: "",
  willpower_temporary: 5,
  willpower_permanent: 5,
  health_level_0s: 3,
  health_level_1s: 3,
  health_level_2s: 3,
  health_level_4s: 1,
  health_level_incap: 1,
  damage_bashing: 0,
  damage_lethal: 0,
  damage_aggravated: 0,
  attr_strength: 5,
  attr_dexterity: 2,
  attr_stamina: 5,
  attr_charisma: 2,
  attr_manipulation: 1,
  attr_appearance: 5,
  attr_perception: 2,
  attr_intelligence: 4,
  attr_wits: 3,
  abil_archery: 0,
  abil_athletics: 3,
  abil_awareness: 2,
  abil_brawl: 5,
  abil_bureaucracy: 2,
  abil_dodge: 0,
  abil_integrity: 1,
  abil_investigation: 0,
  abil_larceny: 0,
  abil_linguistics: 1,
  abil_lore: 3,
  abil_medicine: 0,
  abil_melee: 0,
  abil_occult: 3,
  abil_performance: 0,
  abil_presence: 4,
  abil_resistance: 1,
  abil_ride: 0,
  abil_sail: 0,
  abil_socialize: 0,
  abil_stealth: 0,
  abil_survival: 3,
  abil_thrown: 0,
  abil_war: 0,
  abil_craft: [
    {
      craft: "Weaponsmithing",
      rating: 5,
    },
    {
      craft: "Amoursmithing",
      rating: 1,
    },
    {
      craft: "Tailor",
      rating: 1,
    },
    {
      craft: "Jewelery",
      rating: 4,
    },
    {
      craft: "Artifact",
      rating: 5,
    },
  ],
  abil_martial_arts: [],
  specialties: [
    {
      context: "Intimidation",
      ability: "presence",
    },
    {
      context: "Business Dealing",
      ability: "bureaucracy",
    },
    {
      context: "Feats of Strength",
      ability: "athletics",
    },
    {
      context: "Public Works",
      ability: "lore",
    },
    {
      context: "Weapons",
      ability: "lore",
    },
  ],
  ties: [
    {
      subject: "Handwerksring(Treasure)",
      rating: 3,
    },
    {
      subject: "Circle (Kinship)",
      rating: 2,
    },
    {
      subject: "Lester (Trust)",
      rating: 2,
    },
    {
      subject: "Creations of Others (Respect/Interest)",
      rating: 1,
    },
    {
      subject: "Workshop (Longing)",
      rating: 1,
    },
    {
      subject: "Grandmother Bright (Respect)",
      rating: 1,
    },
  ],
  principles: [
    {
      subject: "Putting all your effort into something is never wrong",
      rating: 3,
    },
    {
      subject: "Do one thing fully and well",
      rating: 3,
    },
    {
      subject: "Things I make are for protecting others",
      rating: 2,
    },
    {
      subject: "I dream of just me and my work undisturbed",
      rating: 1,
    },
    {
      subject: "My creations are my children",
      rating: 1,
    },
    {
      subject: "A deal's a deal",
      rating: 1,
    },
    {
      subject: "Excess opulence is stupid",
      rating: 1,
    },
  ],
  armor_name: "Iron Skin",
  armor_weight: "unarmored",
  armor_is_artifact: false,
  armor_tags: [],
  is_sorcerer: true,
  sorcerous_motes: 10,
  rituals: ["Motes equal to the last sxp I got"],
  lore_background: "",
  native_language: "Riverspeak",
  resources: [],
  xp_total: 0,
  xp_solar_total: 0,
  xp_log: [],
  xp_log_solar: [],
  bp_log: [
    {
      label: "",
      points: 0,
    },
  ],
  xp_craft_silver: 0,
  xp_craft_gold: 0,
  xp_craft_white: 0,
  notes: "",
  equipment: null,
  portrait_link: "",
  motes_personal_current: 16,
  motes_personal_total: 16,
  motes_peripheral_current: 33,
  motes_peripheral_total: 40,
  motes_committed: [
    {
      pool: "peripheral",
      label: "Handwerksring",
      motes: 3,
    },
    {
      pool: "peripheral",
      label: "Bracers",
      motes: 4,
    },
  ],
  anima_level: 0,
  anima_powers: [],
  anima_display: "",
  caste: "twilight",
  exalt_type: "Solar",
  aspect: false,
  limit_trigger: "Disrespecting the efforts of another",
  limit: 0,
  caste_abilities: ["craft", "occult", "lore", "integrity", "bureaucracy"],
  favored_abilities: [
    "athletics",
    "awareness",
    "brawl",
    "presence",
    "resistance",
  ],
  supernal_ability: "craft",
  merits: [
    {
      id: 1622,
      created_at: "2018-05-05T22:46:09.279Z",
      updated_at: "2018-05-06T01:10:24.888Z",
      character_id: 90,
      sort_order: 1525560374,
      label: "+1 -0 health level, -3 to disguise rolls, certainly memorable.",
      merit_name: "Giant",
      rating: 4,
      merit_cat: "innate",
      description:
        "You are a big boy (9ft tall). Hard to pass as anyone of lesser stature.",
      ref: "",
      supernatural: false,
      prereqs: "",
    },
    {
      id: 1623,
      created_at: "2018-05-05T22:46:40.015Z",
      updated_at: "2018-05-06T01:10:10.108Z",
      character_id: 90,
      sort_order: 1525560403,
      label: "+1 non-charm dice to Feats of Strength",
      merit_name: "Mighty Thew",
      rating: 1,
      merit_cat: "purchased",
      description: "Add the rating to feats of strongth",
      ref: "",
      supernatural: false,
      prereqs: "",
    },
    {
      id: 1624,
      created_at: "2018-05-05T22:47:25.332Z",
      updated_at: "2018-05-06T01:10:07.171Z",
      character_id: 90,
      sort_order: 1525560452,
      label:
        "Reduce difficulty of resist infection, sickness and disease by 2.",
      merit_name: "Natural Immunity",
      rating: 2,
      merit_cat: "innate",
      description: "",
      ref: "",
      supernatural: false,
      prereqs: "",
    },
    {
      id: 1625,
      created_at: "2018-05-05T22:51:27.369Z",
      updated_at: "2018-05-06T01:10:05.095Z",
      character_id: 90,
      sort_order: 1525560698,
      label: "Old Realm, High Realm, Rivertongue",
      merit_name: "Language",
      rating: 1,
      merit_cat: "purchased",
      description: "",
      ref: "",
      supernatural: false,
      prereqs: "",
    },
    {
      id: 1626,
      created_at: "2018-05-05T23:39:35.887Z",
      updated_at: "2018-05-06T01:35:05.165Z",
      character_id: 90,
      sort_order: 1525563585,
      label: "Gem of Perfect Mobility (Fire, Greater)",
      merit_name: "Fire Hearthstone",
      rating: 1,
      merit_cat: "story",
      description:
        "2 Evocations available, 6m for acting as if you had +3i and +3 dice for disengage and rush. 3m, 2i for reflex Dexterity action regardless of init order once per scene.",
      ref: "Arms 134",
      supernatural: false,
      prereqs: "",
    },
    {
      id: 1627,
      created_at: "2018-05-05T23:39:39.081Z",
      updated_at: "2018-05-06T01:34:58.347Z",
      character_id: 90,
      sort_order: 1525563582,
      label: "+4 motes/hr, Means +2 intervals when resonant",
      merit_name: "Fire Manse",
      rating: 5,
      merit_cat: "story",
      description:
        "Below Chiaroscuro lies an arrangement of pillars of red jade that belie a circular tomb of 5 corners...",
      ref: "Core p.157-169",
      supernatural: false,
      prereqs: "",
    },
  ],
  weapons: [
    {
      id: 54,
      created_at: "2018-03-29T04:56:31.137Z",
      updated_at: "2018-05-06T01:44:52.386Z",
      character_id: 90,
      sort_order: 1522299399,
      name: "Fist (Iron Skin)",
      weight: "medium",
      tags: [],
      is_artifact: false,
      notes: "",
      ability: "brawl",
      attr: "dexterity",
      damage_attr: "strength",
      bonus_accuracy: 0,
      bonus_damage: 0,
      bonus_defense: 0,
      bonus_overwhelming: 0,
    },
  ],
  spells: [
    {
      id: 13,
      created_at: "2018-03-29T04:48:20.831Z",
      updated_at: "2018-05-06T01:24:56.848Z",
      character_id: 90,
      sort_order: 1522298908,
      name: "Invulnerable Skin of Bronze",
      cost: "0sm, 1wp",
      duration: "instant",
      circle: "terrestrial",
      control: true,
      keywords: [],
      body: "",
      ref: "Core p.471-483",
      categories: ["Defense"],
    },
  ],
  charms: [
    {
      id: 6703,
      created_at: "2018-07-15T08:02:18.400Z",
      updated_at: "2018-07-15T08:02:18.400Z",
      character_id: 90,
      sort_order: 1531641743,
      name: "New Charm",
      charm_type: "Ability",
      cost: "0m",
      timing: "reflexive",
      duration: "instant",
      keywords: [],
      min_essence: 1,
      prereqs: "none",
      body: "",
      ref: "",
      categories: [],
      summary: "",
      ability: "",
      min_ability: 1,
    },
  ],
  martial_arts_charms: [],
  evocations: [
    {
      id: 3911,
      created_at: "2018-05-11T23:42:22.764Z",
      updated_at: "2018-05-11T23:42:22.764Z",
      character_id: 90,
      sort_order: 1526082149,
      name: "New Evocation",
      charm_type: "Evocation",
      cost: "0m",
      timing: "reflexive",
      duration: "instant",
      keywords: [],
      min_essence: 1,
      prereqs: "none",
      body: "",
      ref: "",
      categories: [],
      summary: "",
      artifact_name: "",
    },
  ],
  spirit_charms: [],
}
